baseurl = "https://rom.sexy/"
languageCode = "it-CH"
title = "Cdrrr"
builddrafts = true
theme = "romsexy"
PygmentsCodeFences = true
googleAnalytics = "UA-74722243-1"

[params]
	Subtitle = "Programmatore di <span class='nw'>Omicron Perseo 8</span>"